# Generated by Django 3.2.9 on 2021-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
