# Generated by Django 3.2.9 on 2021-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app7', '0002_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
