# Generated by Django 3.2.9 on 2021-12-02 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_app7', '0003_message_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
