# Generated by Django 3.2.9 on 2021-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('question', 'Pytanie'), ('other', 'Inne')], max_length=16),
        ),
    ]
